/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export {
	PROGRESS_BAR_SIZE_CLASSES,
	PROGRESS_BAR_VARIANT_CLASSES,
	SKELETON_ANIMATION_CLASSES,
	SKELETON_VARIANT_CLASSES,
	SPINNER_COLOR_CLASSES,
	SPINNER_SIZE_CLASSES,
	SPINNER_VARIANT_CLASSES
} from './record';
