export const STYLIST_GRAPH_WORKSPACE_SEED = {
	worldBounds: {
		width: 2200,
		height: 1400
	},
	initialNodes: [
		{
			id: 'north-star',
			title: 'North Star',
			category: 'cluster',
			x: 80,
			y: 110,
			width: 250,
			height: 250,
			color: '#0f172a',
			accent: '#f97316',
			summary: 'Vision anchor for the whole story space.',
			details: ['Mission framing', 'Shared language', 'Decision context'],
			shape: 'circle'
		},
		{
			id: 'research',
			title: 'Research Signals',
			category: 'signal',
			x: 460,
			y: 160,
			width: 310,
			height: 180,
			color: '#0b3b2e',
			accent: '#34d399',
			summary: 'Inputs gathered from interviews, logs, and telemetry.',
			details: ['24 interviews', '312 tagged findings', '7 recurring pain themes'],
			shape: 'rounded'
		},
		{
			id: 'friction-map',
			title: 'Friction Map',
			category: 'insight',
			x: 920,
			y: 100,
			width: 340,
			height: 220,
			color: '#102a43',
			accent: '#60a5fa',
			summary: 'Priority bottlenecks surfaced through synthesis.',
			details: ['Search drop-off', 'Navigation overload', 'Low confidence states'],
			shape: 'rounded'
		},
		{
			id: 'prototype',
			title: 'Prototype Orbit',
			category: 'delivery',
			x: 1410,
			y: 190,
			width: 320,
			height: 200,
			color: '#3f1d5a',
			accent: '#c084fc',
			summary: 'Concept routes that transform signals into outcomes.',
			details: ['Zoomable canvas', 'Semantic zoom', 'Narrative camera path'],
			shape: 'rounded'
		},
		{
			id: 'launch',
			title: 'Launch Loop',
			category: 'delivery',
			x: 1740,
			y: 460,
			width: 300,
			height: 180,
			color: '#4a1d1f',
			accent: '#fb7185',
			summary: 'Release, observe, and feed the next cycle.',
			details: ['Pilot cohort', 'Success metrics', 'Iteration rituals'],
			shape: 'pill'
		},
		{
			id: 'journey',
			title: 'Journey Arc',
			category: 'narrative',
			x: 600,
			y: 470,
			width: 520,
			height: 260,
			color: '#3b2f0d',
			accent: '#fbbf24',
			summary: 'A curated narrative frame connecting insight to execution.',
			details: ['Problem', 'Evidence', 'Direction', 'Prototype', 'Outcome'],
			shape: 'rounded'
		},
		{
			id: 'micro-state',
			title: 'Micro State',
			category: 'signal',
			x: 1230,
			y: 520,
			width: 180,
			height: 180,
			color: '#1f2937',
			accent: '#22c55e',
			summary: 'A small zoom target used to demonstrate point-to-full scaling.',
			details: ['Point mode', 'Summary mode', 'Full mode'],
			shape: 'circle'
		},
		{
			id: 'storyboard',
			title: 'Storyboard',
			category: 'narrative',
			x: 310,
			y: 870,
			width: 420,
			height: 220,
			color: '#0f3057',
			accent: '#38bdf8',
			summary: 'Presentation path converted into a sequence of camera frames.',
			details: ['Overview frame', 'Evidence frame', 'Solution frame', 'Outcome frame'],
			shape: 'rounded'
		},
		{
			id: 'metrics',
			title: 'Outcome Metrics',
			category: 'insight',
			x: 980,
			y: 860,
			width: 360,
			height: 220,
			color: '#3c2415',
			accent: '#fb923c',
			summary: 'Signals used to measure the story after release.',
			details: ['Task completion', 'Confidence gain', 'Narrative comprehension'],
			shape: 'rounded'
		}
	],
	initialConnections: [
		['north-star', 'research'],
		['research', 'friction-map'],
		['friction-map', 'prototype'],
		['prototype', 'launch'],
		['research', 'journey'],
		['journey', 'micro-state'],
		['journey', 'storyboard'],
		['storyboard', 'metrics'],
		['metrics', 'launch']
	]
} as const;
