export const TOKEN_PLAYGROUND_ICON = [
	'playground-ai-assistant',
	'playground-ai-chat',
	'playground-ai-panel',
	'playground-canvas-shell',
	'playground-code-viewer',
	'playground-component-catalog',
	'playground-component-info-card',
	'playground-component-tree',
	'playground-device-frame',
	'playground-drawing-overlay',
	'playground-enhanced-export-panel',
	'playground-error-boundary',
	'playground-generic-code-viewer',
	'playground-live-code-section',
	'playground-markdown-renderer',
	'playground-screenshot-selector',
	'playground-shell-header',
	'playground-shortcuts-panel',
	'playground-tree-node',
	'props-editor',
	'story'
] as const;
