/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export type {
	FoundationAxis,
	FoundationAxisDirection,
	FoundationAxisOrientation,
	TierContent,
	TokenArchitectureIcon,
	TokenArchitectureShaderFragment,
	TokenArchitectureShaderVertex,
	TokenComponentType,
	TokenConnector,
	TokenEasing,
	TokenFunctionalTaxonomy,
	TokenLetterSpacing,
	TokenLineHeight,
	TokenLineType,
	TokenMarker,
	TokenNodeType,
	TokenOpacity,
	TokenOwnership,
	TokenPanMode,
	TokenRelationship,
	TokenSkeleton,
	TokenTrajectory,
	TokenZoom
} from './enum';
export type { FoundationCameraState, FoundationDepth, FoundationSemanticZoomStage } from './script';
export type {
	ArchitectureHTMLAttributes,
	ArchitectureScene,
	CameraState,
	Position2D,
	PresentationMode,
	PresenterNodeShellProps,
	PresenterSceneContract,
	PresenterSceneLink,
	PresenterSceneProps,
	PreziSceneContract,
	SceneAtom,
	SceneAtomGeometry,
	SceneAtomKind,
	SceneAtomMetadata,
	SceneAtomMotion,
	SceneAtomTransform,
	SceneBufferSet,
	SceneCamera,
	SceneCameraInput,
	SceneCameraPreset,
	SceneDebugInfo,
	SceneGeometry,
	SceneGraph,
	SceneInteractionState,
	SceneMaterial,
	SceneMaterialKind,
	SceneMolecule,
	SceneNode,
	SceneNodePoint,
	SceneProps,
	SelectionMode,
	SemanticZoomParams,
	SemanticZoomPresentation,
	StructIntersectAll,
	Zoom,
	ZoomStep
} from './struct';
export type { FoundationDepthThreshold } from './script';
