export type TypeDomainComponentDescriptor = {
	entityPath: string;
	domain: string;
	cluster: 'component';
	joint: 'atom' | 'molecule' | 'organism';
	family: string;
	componentModulePath: string | null;
	recipeTypePath: string | null;
	stateFunctionPath: string | null;
	jsonPaths: string[];
	contractPaths: string[];
	interfaceRecipeJsonPaths: string[];
	constEnumJsonPaths: string[];
	constMapJsonPaths: string[];
	functionStateJsonPaths: string[];
	functionScriptJsonPaths: string[];
	controlDefinitionJsonPaths: string[];
	hasRecipePipeline: boolean;
	hasStatePipeline: boolean;
	hasStoryPreview: boolean;
	storyModulePath: string | null;
};
