import type { ContractAnnouncementBanner } from '$stylist/media/interface/contract/announcement-banner';
import type { ContractAudioPlayer } from '$stylist/media/interface/contract/audio-player';
import type { ContractAudioSlider } from '$stylist/media/interface/contract/audio-slider';
import type { ContractAudioVisualizer } from '$stylist/media/interface/contract/audio-visualizer';
import type { ContractAvatarGroup } from '$stylist/media/interface/contract/avatar-group';
import type { ContractAvatar } from '$stylist/media/interface/contract/avatar';
import type { ContractCanvasImageEditor } from '$stylist/media/interface/contract/canvas-image-editor';
import type { ContractCountryFlag } from '$stylist/media/interface/contract/country-flag';
import type { ContractFavicon } from '$stylist/media/interface/contract/favicon';
import type { ContractIcon } from '$stylist/media/interface/contract/icon';
import type { ContractImageGallery } from '$stylist/media/interface/contract/image-gallery';
import type { ContractImageWithCaption } from '$stylist/media/interface/contract/image-with-caption';
import type { ContractImage } from '$stylist/media/interface/contract/image';
import type { ContractMediaLibrary } from '$stylist/media/interface/contract/media-library';
import type { ContractNodeIcon } from '$stylist/media/interface/contract/node-icon';
import type { ContractPromoBanner } from '$stylist/media/interface/contract/promo-banner';
import type { ContractSvg } from '$stylist/media/interface/contract/svg';
import type { ContractTeamAvatarStack } from '$stylist/media/interface/contract/team-avatar-stack';
import type { ContractVideoPlayer } from '$stylist/media/interface/contract/video-player';

export interface ContractMedia {
	AnnouncementBanner: ContractAnnouncementBanner;
	AudioPlayer: ContractAudioPlayer;
	AudioSlider: ContractAudioSlider;
	AudioVisualizer: ContractAudioVisualizer;
	Avatar: ContractAvatar;
	AvatarGroup: ContractAvatarGroup;
	CanvasImageEditor: ContractCanvasImageEditor;
	CountryFlag: ContractCountryFlag;
	Favicon: ContractFavicon;
	Icon: ContractIcon;
	Image: ContractImage;
	ImageGallery: ContractImageGallery;
	ImageWithCaption: ContractImageWithCaption;
	MediaLibrary: ContractMediaLibrary;
	NodeIcon: ContractNodeIcon;
	PromoBanner: ContractPromoBanner;
	Svg: ContractSvg;
	TeamAvatarStack: ContractTeamAvatarStack;
	VideoPlayer: ContractVideoPlayer;
}
