/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { ANNOUNCEMENT_BANNER_CLASSES } from './map';
export {
	IMAGE_WITH_CAPTION_CLASSES,
	RECORD_ICON_SIZE,
	TOKEN_ICON_REGISTRY,
	TOKEN_MEDIA_ICON
} from './record';
