/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export {
	COLORS_SCALES_AMBER,
	COLORS_SCALES_BLUE,
	COLORS_SCALES_GRAY,
	COLORS_SCALES_GREEN,
	COLORS_SCALES_NEUTRAL,
	COLORS_SCALES_RED,
	COLORS_SCALES_SLATE,
	COLORS_SCALES_TEAL
} from './colors-scales';
